spring:
  application:
    name: CmsApi
  datasource:
    name: cms_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: adminadmin