spring:
  application:
    name: CmsApi
  datasource:
    name: cms_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: adminadmin